
# liveBaseRoute: synergy-concept-backend.onrender.com

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMjM1ZjMxMDQtNWZjNS00MjJkLTllMGEtNGQ2MzdiZDMwMGI0IiwiZW1haWwiOiJqZGYxenhtMmZiQHduYmFsZHd5LmNvbSIsInJvbGUiOiJzdXBlcl9hZG1pbiIsInNjaG9vbElkIjoiMGI5NzI2OGMtYzM0YS00MDQxLWFhZDEtZDVmMjEyZWMwOTY0IiwidmVyaWZpZWQiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjUtMTEtMDVUMTM6Mzc6NTQuMjUwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMTEtMDVUMTM6Mzc6NTQuMjUwWiIsInN0dWRlbnRQcm9maWxlIjpudWxsLCJzdGFmZlByb2ZpbGUiOm51bGwsInBhcmVudFByb2ZpbGUiOm51bGwsInN1cGVyQWRtaW5Qcm9maWxlIjp7ImlkIjoiMTIyNzg5MTAtNTI1NS00Njg2LTkwYmMtMWM5NTRkNzBjOTRhIiwidXNlcklkIjoiMjM1ZjMxMDQtNWZjNS00MjJkLTllMGEtNGQ2MzdiZDMwMGI0IiwiZmlyc3ROYW1lIjoiVGVtaXRvcGUiLCJsYXN0TmFtZSI6IkRhcmFtb2xhIiwiZ2VuZGVyIjpudWxsLCJjcmVhdGVkQXQiOiIyMDI1LTExLTA1VDEzOjM3OjU0LjI1MFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTA1VDEzOjM3OjU0LjI1MFoifX0sIm5hbWUiOiJhY2Nlc3MiLCJpYXQiOjE3NjIzNDk5NzEsImV4cCI6MTc2Mjk1NDc3MX0.yacPnDd614oH0v8ICN7Q9BF_bn1_04bTSgnkOK9ESgg
# SIGNUP
#####
##################################
# POST https://synergy-concept-backend.onrender.com/api/auth/signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "firstName": "Temitope",
    "lastName": "Daramola",
    "email": "jdf1zxm2fb@wnbaldwy.com",
    "password": "12345678"
}


###############################################
# ### https://synergy-concept-backend.onrender.com/
#### LOGIN
# POST http://localhost:3000/api/auth/login
POST https://synergy-concept-backend.onrender.com/api/auth/login
Content-Type: application/json

{
    "email": "sevaca5636@keevle.com",
    "password": "12345678"
}


###################################
# VERIFY
POST http://localhost:3000/api/auth/verify
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiamRmMXp4bTJmYkB3bmJhbGR3eS5jb20ifSwibmFtZSI6ImF1dGgiLCJpYXQiOjE3NjIzNDk4NzAsImV4cCI6MTc2MjM1MTY3MH0.Tii5f18LRef31NH0bvJZRY6qoLBZ6IesY_1f9EvsL6o"
}

###################################
# RESEND VERIFY
GET http://localhost:3000/api/auth/verify/m9ikerl@onmailflare.com
Content-Type: application/json


#########################################
# INIT ACCOUNT
GET http://localhost:3000/auth/user/init-account/johndoe@givmail.com
Content-Type: application/json

#########################################
# INIT ACCESS TOKEN
GET http://localhost:3000/auth/user/refresh-access-token/johndoe@givmail.com
Content-Type: application/json


