

# CREATE
POST http://localhost:3000/api/school-info
# POST https://synergy-concept-backend.onrender.com/api/school-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMjM1ZjMxMDQtNWZjNS00MjJkLTllMGEtNGQ2MzdiZDMwMGI0IiwiZW1haWwiOiJqZGYxenhtMmZiQHduYmFsZHd5LmNvbSIsInJvbGUiOiJzdXBlcl9hZG1pbiIsInNjaG9vbElkIjoiMGI5NzI2OGMtYzM0YS00MDQxLWFhZDEtZDVmMjEyZWMwOTY0IiwidmVyaWZpZWQiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjUtMTEtMDVUMTM6Mzc6NTQuMjUwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMTEtMDVUMTM6Mzc6NTQuMjUwWiIsInN0dWRlbnRQcm9maWxlIjpudWxsLCJzdGFmZlByb2ZpbGUiOm51bGwsInBhcmVudFByb2ZpbGUiOm51bGwsInN1cGVyQWRtaW5Qcm9maWxlIjp7ImlkIjoiMTIyNzg5MTAtNTI1NS00Njg2LTkwYmMtMWM5NTRkNzBjOTRhIiwidXNlcklkIjoiMjM1ZjMxMDQtNWZjNS00MjJkLTllMGEtNGQ2MzdiZDMwMGI0IiwiZmlyc3ROYW1lIjoiVGVtaXRvcGUiLCJsYXN0TmFtZSI6IkRhcmFtb2xhIiwiZ2VuZGVyIjpudWxsLCJjcmVhdGVkQXQiOiIyMDI1LTExLTA1VDEzOjM3OjU0LjI1MFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTA1VDEzOjM3OjU0LjI1MFoifX0sIm5hbWUiOiJhY2Nlc3MiLCJpYXQiOjE3NjIzNDk5NzEsImV4cCI6MTc2Mjk1NDc3MX0.yacPnDd614oH0v8ICN7Q9BF_bn1_04bTSgnkOK9ESgg

{
    "name": "Bright International School",
    "email": "brightintrnational@gmail.com",
    "phoneNumber1": "09029886869",
    "country": "Nigeria",
    "state": "Oyo",
    "address": "University Of Ibadan, Ibadan"
}


# UPDATE#
###############################################
# PUT http://localhost:3000/api/school-info
PUT https://synergy-concept-backend.onrender.com/api/school-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMTZiNTEyMDItZmI2Yy00MDE4LWFhZGQtNDY0MTVjN2RjOTZmIiwiZW1haWwiOiJzZXZhY2E1NjM2QGtlZXZsZS5jb20iLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJzY2hvb2xJZCI6IjU0MDU1ZTQxLWFhMjAtNDc2MS05NTcwLWFiODgzNjRhMmRjOCIsInZlcmlmaWVkIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDI1LTEwLTI4VDEyOjEwOjQ3LjgzMloiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTAxVDExOjE5OjMzLjEzM1oiLCJzdHVkZW50UHJvZmlsZSI6bnVsbCwic3RhZmZQcm9maWxlIjpudWxsLCJwYXJlbnRQcm9maWxlIjpudWxsLCJzdXBlckFkbWluUHJvZmlsZSI6eyJpZCI6ImVhMzIzM2ZkLTdmN2EtNGE5OS1hMjNhLWE3MjNkZjlhZDc1OCIsInVzZXJJZCI6IjE2YjUxMjAyLWZiNmMtNDAxOC1hYWRkLTQ2NDE1YzdkYzk2ZiIsImZpcnN0TmFtZSI6IlRlbWl0b3BlIiwibGFzdE5hbWUiOiJEYXJhbW9sYSIsImdlbmRlciI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0xMC0yOFQxMjoxMDo0Ny44MzJaIiwidXBkYXRlZEF0IjoiMjAyNS0xMC0yOFQxMjoxMDo0Ny44MzJaIn19LCJuYW1lIjoiYWNjZXNzIiwiaWF0IjoxNzYyMzMyMDM3LCJleHAiOjE3NjI5MzY4Mzd9.pGNbeHUO8uBa69ov5gmcGR-7HxgNqwR0Y-CuD-dmCPI

{
    "id": "54055e41-aa20-4761-9570-ab88364a2dc8",
    "name": "Bright International School Nigeria",
    "date": "N/A"
}


###################################
GET http://localhost:3000/api/school-info?id=0b97268c-c34a-4041-aad1-d5f212ec0964
# GET https://synergy-concept-backend.onrender.com/api/school-info?id=0b97268c-c34a-4041-aad1-d5f212ec0964
Content-Type: application/json

